fix: Dockerfile and pipeline

diff --git a/.github/workflows/cicd-pipeline.yml b/.github/workflows/cicd-pipeline.yml
--- a/.github/workflows/cicd-pipeline.yml
+++ b/.github/workflows/cicd-pipeline.yml
@@ -4,13 +4,69 @@ on:
   push:
     branches:
       - main
+
   pull_request:
     types: [opened, synchronize, reopened]
 
 jobs:
-  build-and-publish:
+  test:
+    if: false
     runs-on: ubuntu-latest
 
+    permissions:
+      contents: read
+      checks: write  # Permitir la creación de checks de GitHub
+
+    steps:
+      - name: Check out the repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
+        with:
+          java-version: '21'
+          distribution: 'adopt'
+
+      - name: Cache Maven dependencies
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Install dependencies
+        run: mvn install -DskipTests
+
+      - name: Prepare native libs folder and copy library
+        run: cp lib/libbisection.so /usr/lib/
+
+      - name: Run Tests with Testcontainers and Generate Coverage Report
+        env:
+          TESTCONTAINERS_RYUK_DISABLED: "true" # Opcional: deshabilita Ryuk si es necesario
+          DOCKER_HOST: tcp://localhost:2375
+        run: mvn test jacoco:report
+
+      - name: Upload Test and Coverage Results
+        if: always()  # Este paso se ejecuta incluso si las pruebas fallan
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-results
+          path: |
+            target/surefire-reports
+            target/site/jacoco/jacoco.xml
+
+      - name: Display Test Results
+        uses: dorny/test-reporter@v1
+        with:
+          name: Test Results
+          path: target/surefire-reports/*.xml
+          reporter: java-junit
+
+  build-and-publish:
+    runs-on: ubuntu-latest
     steps:
       - name: Check out the repository
         uses: actions/checkout@v4
@@ -24,9 +80,6 @@ jobs:
       - name: Build JAR
         run: mvn clean package -DskipTests
 
-      - name: Verify JAR file exists
-        run: ls -l target/punto-equilibrio-1.0.0.jar
-
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
         with:
@@ -35,13 +88,13 @@ jobs:
 
       - name: Build and Push Docker Image
         run: |
-          docker build --progress=plain --no-cache -t angiecobo/ova-costos:latest .
-          docker push angiecobo/ova-costos:latest
+          docker build -t joseloaiza01/ova-analisis:latest .
+          docker push joseloaiza01/ova-analisis:latest
 
   deploy:
+    if: true
     needs: build-and-publish
     runs-on: ubuntu-latest
-    if: true
 
     steps:
       - name: Check out repository
@@ -52,8 +105,8 @@ jobs:
       - name: Verify compose.yaml Exists
         run: |
           if [ ! -f compose.yaml ]; then
-            echo "Error: compose.yaml not found!"
-            exit 1
+          echo "Error: compose.yaml not found!"
+          exit 1
           fi
 
       - name: Create SSH Key File
@@ -62,21 +115,24 @@ jobs:
           echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
-      - name: Add Host to known_hosts
-        run: |
-          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
-
       - name: Create directory on EC2
         uses: appleboy/ssh-action@v0.1.8
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
-          script: mkdir -p ~/app-costos
+          script: |
+            mkdir -p ~/app-receiver-iot
 
-      - name: Copy docker-compose.yaml to EC2
+      - name: Add Host to known_hosts
         run: |
-          scp -i ~/.ssh/id_rsa ./compose.yaml ubuntu@${{ secrets.EC2_HOST }}:~/app-costos/compose.yaml
+          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+
+      - name: Copy docker-compose.yml to EC2
+        env:
+         EC2_HOST: ${{ secrets.EC2_HOST }}
+        run: |
+          scp -i ~/.ssh/id_rsa ./compose.yaml ubuntu@$EC2_HOST:~/app-receiver-iot/compose.yaml
 
       - name: Run Docker Compose on EC2
         uses: appleboy/ssh-action@v0.1.8
@@ -84,7 +140,8 @@ jobs:
           host: ${{ secrets.EC2_HOST }}
           username: ubuntu
           key: ${{ secrets.EC2_SSH_KEY }}
+          command_timeout: 10m
           script: |
-            cd ~/app-costos
+            cd ~/app-receiver-iot
             sudo docker compose --profile app pull
-            sudo docker compose --profile app up -d
+            sudo docker compose --profile app up -d          
